title: Reece's Pages
description: Articles on things I find interesting

author:
  name: Reece Jones
  email: "reece.jones131@gmail.com"

timezone: Australia/Sydney

defaults:
  -
    scope:
      path: _posts
    values:
      layout: post

permalink: "/articles/:title"

plugins:
  - jekyll-remote-theme
  - jekyll-feed

remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%Y %B %d"
  social_links:
    - { platform: github, user_url: "https://github.com/MC-DeltaT" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/reece-jones-1327261a3/" }
